server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/university-course
    username: postgres
    password: 201086
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true